from django.urls import path
from . import views


urlpatterns = [
    path('',views.login),
    path('register/',views.register),
    path('view_users/',views.view_users),
    path('otp/',views.otp_check),
    path('forgetpass/',views.forgetpass),
    path('resetpass/',views.resetpass),
    path('google_signup/',views.google_signup),
    path('google_login/',views.google_login),
    path('payment/',views.payment),
    path('profile_view/',views.profile_view),
    path('delete_user/<int:id>/',views.delete_user),
    path('edit_profile/',views.edit_profile),
    path('chat_bot/',views.chat_bot),
    path('haspremium/',views.haspremium),
    path('nopremium/',views.nopremium),
    path('user_complaints/',views.user_complaints),
    path('get_complaints/',views.get_complaints),
    path('send_reply/',views.send_reply),
    path('get_allcomplaints/',views.get_allcomplaints),
    path('revenue_flow_chart/',views.revenue_flow_chart),
    path('get_data/',views.get_data),
    path('mate_finding/',views.mate_finding),
    path('log_user/',views.log_user),
    path('chat/',views.chats),
    path('user_list/',views.user_list),
    path('get_all_chats/',views.get_all_chats),
    path('get_chats/',views.get_chats),
    path('current_user/',views.current_user),
    path('other_user/',views.other_user),
    path('send_request/',views.send_request),
    path('get_request/',views.get_request),
    path('accept/',views.accept),
    path('get_all_request/',views.get_all_request),
    path('reject/',views.reject),
    path('api/calls/start_call/', views.start_call, name='start_call'),
    path('api/calls/accept_call/', views.accept_call, name='accept_call'),
    path('api/calls/reject_call/', views.reject_call, name='reject_call'),
    path('api/calls/cancel_call/', views.cancel_call, name='cancel_call'),
    path('api/calls/end_call/', views.end_call, name='end_call'),
    path('api/calls/check_call_status/', views.check_call_status, name='check_call_status'),
    path('api/calls/generate_zego_token/', views.generate_zego_token, name='generate_zego_token'),
    path('api/calls/check_incoming/', views.check_incoming, name='check_incoming'),
    path('api/calls/active_calls/', views.active_calls, name='active_calls'),
    path('api/calls/create/', views.create_call, name='create_call'),
    path('api/calls/status/', views.call_status, name='call_status'),
    path('api/calls/join/', views.join_call, name='join_call'),
    path('get_users_match/', views.get_users_match),
    path('view_profile/', views.view_profile),
    path('check_premium/', views.check_premium),
    path('update_time/', views.update_time),
    path('check_online/', views.check_online),
   
]
