# Generated by Django 3.2.25 on 2025-10-19 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dating', '0002_auto_20251013_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_registration',
            name='username',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
