# Generated by Django 3.2.25 on 2025-10-20 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dating', '0003_user_registration_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_registration',
            name='profile',
            field=models.ImageField(blank=True, default='default/0d64989794b1a4c9d89bff571d3d5842.jpg', null=True, upload_to='profile'),
        ),
    ]
