# Generated by Django 5.2.7 on 2025-11-01 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dating', '0004_user_registration_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_registration',
            name='premium',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
