# Generated by Django 5.2.7 on 2025-11-01 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dating', '0005_user_registration_premium'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_registration',
            name='premium',
            field=models.CharField(blank=True, default='false', max_length=50, null=True),
        ),
    ]
