# Generated by Django 5.2.7 on 2025-11-03 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dating', '0006_alter_user_registration_premium'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaints', models.CharField(blank=True, max_length=100, null=True)),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dating.user_registration')),
            ],
        ),
    ]
