# Generated by Django 5.2.7 on 2025-11-03 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dating', '0007_complaints'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaints',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
