# Generated by Django 5.2.7 on 2025-11-05 09:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dating', '0009_complaints_resolved'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_registration',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
