# Generated by Django 5.2.7 on 2025-11-13 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dating', '0013_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
