# Generated by Django 5.2.7 on 2025-11-15 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dating', '0015_friend_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='friend_request',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
