# Generated by Django 5.2.7 on 2025-11-18 06:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dating', '0016_friend_request_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(max_length=100)),
                ('call_type', models.CharField(max_length=10)),
                ('token', models.CharField(max_length=200)),
                ('accepted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calls_received', to='dating.user_registration')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calls_made', to='dating.user_registration')),
            ],
        ),
    ]
