# Generated by Django 5.2.7 on 2025-11-18 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dating', '0017_callrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='callrequest',
            name='status',
            field=models.CharField(default='pending', max_length=10, null=True),
        ),
    ]
