# Generated by Django 5.2.7 on 2025-11-18 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dating', '0018_callrequest_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='callrequest',
            name='accepted',
        ),
    ]
