# Generated by Django 5.2.7 on 2025-11-18 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dating', '0019_remove_callrequest_accepted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='callrequest',
            name='token',
        ),
        migrations.AlterField(
            model_name='callrequest',
            name='channel',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='callrequest',
            name='status',
            field=models.CharField(default='pending', max_length=10),
        ),
    ]
