# Generated by Django 5.2.7 on 2025-11-23 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dating', '0023_alter_user_registration_isonline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_registration',
            name='isonline',
            field=models.CharField(blank=True, default='offline', max_length=50, null=True),
        ),
    ]
