# Generated by Django 5.2.7 on 2025-11-23 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dating', '0024_alter_user_registration_isonline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_registration',
            name='last_active',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
