# Generated by Django 6.0.1 on 2026-03-02 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dating', '0025_alter_user_registration_last_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_registration',
            name='profile',
            field=models.ImageField(blank=True, null=True, upload_to='profile'),
        ),
    ]
