# Generated by Django 5.2.7 on 2025-11-04 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dating', '0008_complaints_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaints',
            name='resolved',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
