# Generated by Django 5.2.7 on 2025-11-09 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dating', '0010_user_registration_date_joined'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_registration',
            name='hobbies',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
