# Generated by Django 5.2.7 on 2025-11-09 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dating', '0011_user_registration_hobbies'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_registration',
            old_name='hobbies',
            new_name='hobies',
        ),
    ]
