# Generated by Django 5.2.7 on 2025-11-23 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dating', '0020_remove_callrequest_token_alter_callrequest_channel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_registration',
            name='isonline',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
