# Generated by Django 5.2.7 on 2025-11-23 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dating', '0021_user_registration_isonline'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_registration',
            name='last_active',
            field=models.DateField(blank=True, null=True),
        ),
    ]
