# Generated by Django 5.2.7 on 2025-11-23 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dating', '0022_user_registration_last_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_registration',
            name='isonline',
            field=models.BooleanField(blank=True, default='offline', null=True),
        ),
    ]
